name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: FileUtils
      id: fileutils
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FileUtils
        setup-command: cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -B build && cmake
          --build build
        command: ./build/Test --test-case="FileUtils"
        timeout: 10
        max-score: 25
    - name: RedBlackSearchOperations
      id: redblacksearchoperations
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: RedBlackSearchOperations
        setup-command: cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -B build && cmake
          --build build
        command: ./build/Test --test-case="RedBlackSearchOperations"
        timeout: 10
        max-score: 25
    - name: RedBlackSearchEdgeCount
      id: redblacksearchedgecount
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: RedBlackSearchEdgeCount
        setup-command: cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -B build && cmake
          --build build
        command: ./build/Test --test-case="RedBlackSearchEdgeCount"
        timeout: 10
        max-score: 25
    - name: RedBlackTreeEdgeCount
      id: redblacktreeedgecount
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: RedBlackTreeEdgeCount
        setup-command: cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -B build && cmake
          --build build
        command: ./build/Test --test-case="RedBlackTreeEdgeCount"
        timeout: 10
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FILEUTILS_RESULTS: "${{steps.fileutils.outputs.result}}"
        REDBLACKSEARCHOPERATIONS_RESULTS: "${{steps.redblacksearchoperations.outputs.result}}"
        REDBLACKSEARCHEDGECOUNT_RESULTS: "${{steps.redblacksearchedgecount.outputs.result}}"
        REDBLACKTREEEDGECOUNT_RESULTS: "${{steps.redblacktreeedgecount.outputs.result}}"
      with:
        runners: fileutils,redblacksearchoperations,redblacksearchedgecount,redblacktreeedgecount
